apps/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.hub, name='hub'),
    path('determinant', views.determinant_calc, name='determinant'), 
    path('produto', views.product_calc, name='product'),
    path('binomial', views.binomial, name='binomial'),
    path('pascal', views.pascal, name='pascal'),
    path('pa', views.pa, name='pa'),
    path('pg', views.pg, name='pg'),
    path('add', views.add_element, name='add'),
    path("add/matriz", views.add_matrix, name='add_matrix'),
    path('add/funcao', views.add_function, name='add_function'),
    path('historico/normal', views.historic, name='historic'),
    path('historico', views.historic_hub, name = 'historic_hub'),
    path('historico/matrizes', views.historic_matrices, name='historic_matrices'),
    path('historico/funcao' , views.historic_functions, name='historic_function'),
    path('editar/<int:id>', views.edit, name='edit'),
    path('editar/matriz/<int:id>', views.edit_matrix, name='edit_matrix'),
    path('editar/funcao/<int:id>', views.edit_function, name='edit_function'),
    path('remover/<int:id>', views.remove_normal, name='remove_normal'),
    path('remover/matriz/<int:id>', views.remove_matrix, name='remove_matrix'),
    path('remover/funcao/<int:id>', views.remove_function, name='remove_function'),
    path('funcao', views.function, name='function')
]

estudologia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('apps/', include('apps.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("registrar", views.register, name="register"),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('sobre', views.about_me, name="about_me"),
    path('cursos', views.courses, name='courses'),
    path('cursos/<str:course_url>', views.course, name='course'),
    path('cursos/atualizar/<int:id>', views.updateCourse, name='update_course'),
    path('cursos/pesquisar/categoria/<str:category>/<str:local>', views.search_by_category , name='search'),
]

home/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class User(AbstractUser):
    pass
    def __str__(self):
        return f"{self.username}"
    
class Course(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=90, default='http://127.0.0.1:8000/')
    abstract = models.TextField()
    content = models.TextField()
    link = models.TextField()
    image = models.ImageField(default="course_image.png")
    CATEGORY_CHOICES =(('M', 'Matemática'),('L', 'Linguagens'),('N', 'Ciências da Natureza'), ('H','Ciências Humanas'))
    category = models.CharField(max_length=1 ,choices = CATEGORY_CHOICES , default='A')

    def __str__(self):
        return f"{self.name}"

class Inventory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course, blank=True)
    def __str__(self):    
        return f"{self.user}"
    
class Historic(models.Model):
    APPS_CHOICES = (('pa', 'PA'), ('pg', 'PG'),('ps', 'Pascal'), ('bi', "Binômio de Newton"))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type_app = models.CharField(max_length = 2, choices= APPS_CHOICES)
    var1 = models.FloatField(blank = True, null = True)
    var2 = models.FloatField(blank = True, null = True)
    date = models.DateTimeField(blank = True, null = True)

    def __str__(self):
        return f"{self.user}: {self.type_app} - var1:{self.var1}, var:{self.var2} - time: {self.date}"
    
class MatricesHistoric(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    determinant = models.BooleanField(null = True ,blank = True, default = False)
    date = models.DateTimeField(null = True, blank = True)
    number_rows_a = models.IntegerField(null = False, blank = False, default = 0)
    number_colunms_a = models.IntegerField(null = False, blank = False, default = 0)
    number_rows_b = models.IntegerField(null = True, blank = True)
    number_colunms_b = models.IntegerField(null = True, blank = True)
    matrix_a = models.TextField(null=False, blank = False, default = '[]')
    matrix_b = models.TextField(null=True, blank = True)

class FunctionHistoric(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    date = models.DateTimeField()
    function = models.TextField(blank = False, null = False, default = 'x')


   

home/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(label='Usuário', widget=forms.TextInput({ "placeholder": "Usuário"}))
    password = forms.CharField(widget=forms.PasswordInput, label="Senha",)
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Confirmar Senha",)

class LoginForm(forms.Form):
    username = forms.CharField(label='Usuário', widget=forms.TextInput({ "placeholder": "Usuário"}))
    password = forms.CharField(widget=forms.PasswordInput, label="Senha")

home/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.paginator import Paginator
from .models import *
import json
from datetime import date
from .forms import RegisterForm, LoginForm
from home.models import *

# Create your views here.
def home(request):
    return render(request, "home\home.html")

def login_view(request):
    if request.method == "POST":
       form = LoginForm(request.POST)
       if form.is_valid():
           #get the data
           username = form.cleaned_data["username"]
           password = form.cleaned_data['password']
           user = authenticate(request, username=username, password=password)
           if user is not None:
               login(request, user)
               return HttpResponseRedirect(reverse("home"))
           else:
                return render(request, "home/login.html", {
                "msg": "Usuário ou senha inválido.", 'form' : form
            })
               
    else:
        return render(request, 'home\login.html', {'form' : LoginForm})
       

def logout_view(request):
    try:
        logout(request)
        del request.session[request.user.id]
    except KeyError:
        pass
    return HttpResponseRedirect(reverse("login"))
   


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            confirm_password = form.cleaned_data['confirm_password']
            if(password != confirm_password):
                return render(request, "home/register.html", {'form' : RegisterForm,
                "msg": "Senhas devem ser iguais."
            })
            
            try:
                user = User.objects.create_user(username,  password)
                user.save()
                login(request,user)
                new_inventory = Inventory(user = user)
                new_inventory.save()
            except IntegrityError:
                return render(request, "home/register.html", { 'msg' : 'Usuário já foi registrado tente outro.' ,'form' : RegisterForm})

            return HttpResponseRedirect(reverse('home'))
    else:
        return render(request, "home/register.html", {'form' : RegisterForm})


def about_me(request):
    return render(request, 'home/about_me.html')


def courses(request):
    global avaialble_courses_msg, my_courses_msg
    try:
        available_courses = []
        all_courses = Course.objects.all()
        courses_of_user = Inventory.objects.get(user = request.user).courses.all()
        print(courses_of_user)

#check if the uses at least one course added, because with a empty Inventory the for lopo can't be done
        if len(courses_of_user) == 0:
            available_courses = Course.objects.all()
            #message that you be used on rendering
            my_courses_msg = 'Tente adicionar um curso!'
        
#for loop to know what courses has been added by the user
        else:
         my_courses_msg = ''
         for course in all_courses:
            if course in courses_of_user:
            #if the course exists in the inventory of the user, nothing is done
                pass
            else:
                available_courses.append(course)

        if len(available_courses) == 0:
            avaialble_courses_msg = "Não há curso disponível."
        else:
            avaialble_courses_msg = ''
            

        if request.user.is_authenticated:
            print("logged")
            return render(request, 'home\courses.html', {"avaialble_courses" : available_courses, "avaialble_courses_msg" : avaialble_courses_msg , 'my_courses' : courses_of_user , 'my_courses_msg' : my_courses_msg})
    except Exception as error:
        print(error)
        print("anonimo")
        available_courses = Course.objects.all()
        return render(request, 'home\courses.html', {"avaialble_courses" : available_courses, "my_courses_msg" : "Tente adicionar um curso!" })


def course(request, course_url):
    print(course_url)
    return render(request, 'home\course_page.html',{'course' : Course.objects.get(url = course_url)})

def updateCourse(request, id):
    print(id)
    user = request.user
    object = Inventory.objects.get(user = user)
    course = Course.objects.get(id = id)
    if Course.objects.get(id = id) in Inventory.objects.get(user = user).courses.all():
        print('removing')
        object.courses.remove(Course.objects.get(id = id)) 
        object.save()
        return JsonResponse({'id' : course.id  ,'url' : course.url, 'name' : course.name, 'abstract' : course.abstract, 'link' : course.link, 'image' : course.image.url})
    else:
        print('adding')
        object.courses.add(Course.objects.get(id = id)) 
        object.save()
        return JsonResponse({'id' : course.id, 'url' : course.url, 'name' : course.name, 'abstract' : course.abstract, 'link' : course.link, 'image' : course.image.url})

def search_by_category(request, category, local):
    user = request.user
    ids = []
    object = Inventory.objects.get(user = user)
# courses is the courses that has in the inv
    courses = object.courses.all()
    for course in courses:
        ids.append(course.id)
    if category == 'A':
# If the category is Akk abd the len is 0 will show a message saying that the user can add course
        if local == 'my':
            if len(ids) == 0:
                return JsonResponse({'ids' : ids , 'msg' : 'Tente adicionar um curso!'})
            else:
                return JsonResponse({'ids' : ids})
        else:
# part of the avaialble courses
            if len(ids) == 0:
                for course in Course.objects.all():
                    ids.append(course.id)
                return JsonResponse({'ids' : ids})
            if len(ids) == 8:
                return JsonResponse({'ids' : -1, 'msg' : 'Não há nenhum curso disponível'})
            else:
                all_ids = []
                dis_ids = []
                for course in Course.objects.all():
                    all_ids.append(course.id)
                for id in all_ids:
                    if id in ids:
                        pass
                    else:
                        dis_ids.append(id)
                return JsonResponse({"ids" : dis_ids})


    if(local == 'my'):
# Will create another coueses with the filter method
        courses = courses.filter(category = category).all()
        ids = []
        for course in courses:
            ids.append(course.id)
        if(len(ids) == 0):
            return JsonResponse({'ids' : ids, 'msg' : 'Não há nenhum curso nessa categoria escolhida.'})
        return JsonResponse({'ids' : ids})

    else:
        ids = []
        all_ids = []
        avaialble_course = []
        for course in Course.objects.all():
# If the course is not in courses this means that the couse in avaialble
           if course in courses:
               pass
           else:
               avaialble_course.append(course)
        for course in avaialble_course:
            if course.category == category:
                ids.append(course.id)

        if(len(ids) == 0):
             return JsonResponse({'ids' : ids, 'msg' : 'Não há nenhum curso nessa categoria escolhida.'})
        return JsonResponse({'ids' : ids})
               
        
    

home/templates/home/about_me.html
{% extends 'home/layout.html' %}
{% load static %}
{% block title %}Sobre Mim{% endblock %}
{% block body %}
<div class="content">
    <div class="text_content_about">
        <h1>Sobre Mim</h1>
          <p>Olá eu sou um  estudante do ensino médio apaixonado por tecnologia e ciências e programar se tornou um hobby e uma possível possibilidade de emprego para mim</p>
          <p>Eu criei esse site com o intuito de divulgar conhecimento, sendo uma tentativa minha de alterar o precário cenário educacional que existe no nosso país.</p>
    </div>
  
   
</div>    

{% endblock %}

home/templates/home/br.html
{% extends 'home/layout.html' %}

{% block title %} Home {% endblock %}

{% block body %}
<div class="content">
    <h1 >Ensaios sobre a inteligência feito por um estudante do ensino médio.</h1>
    <p >Nas palestras do Prof Pier, um italo brasileiro notório nas discussões sobre aprendizado e inteligência, o mesmo enfatizava o fato de que a inteligência não é uma característica nata de algúem, mas que como qualquer outra habilidade que o ser humano pode carregar, a capacidade de "ser inteligente" é algo que tem como aprender e desenvolver, ou seja é possível exercitar esse tal dom da inteligência. </p>
    <p >Os estudos são essencias para a vida de qualquer pessoa, pois eles edificam o sujeito, permitindo que ele aprenda novas habilidades as quais podem ser empregadas no seu dia a dia para resolver problemas ou para melhorar algum campo da existencia humana, como a esfera emocional, intelectual e a ate mesmo a espiritual.</p>
    <h2 >Inteligência para a neurociência</h2>
    <p >Estudos contemporâneos da neurociência indicam que é possível qualquer pessoa aumentar o seu conhecimento sobre determinado assunto, seja com maior ou menor esforço a depender de deficiencias cognitivas, mas sempre há espaço de aprendizagem, isso se da pela neuroplasticidade, termo que define a capacidade do nosso cérebro, órgão do corpo humano mais complexo, tem de se moldar de acordo com os estímulos o qual é exposto.</p>

    <h2 >Como aprendemos</h2>
    <p >O aprendizado humano ocorre por meio da visualização de informações e a operação dessas para a realização de alguma atividade - uma questão de prova por exemplo-, por isso o fato de revisar e exercitar essa nova habilidade é de extrema importância, pois somente assim esse conhecimeto é consolidado.</p>
    <h3 >Como apender e lembrar de algo</h3>
    <p >O livro "Aprendendo A Aprender" de Barbara Okley aponta que para aprendermos algo, e com efeito lembrarmos disso , é necessário que exista um dado  e que ele seja memorável, ou seja exista elementos nesse conteúdo estudado  que facilitem a sua retomada da memória, por isso que quanto mais 'inputs' mentais melhor, porque aumentam as chances de você recordar do conteúdo, esses inputs podem ser uma imagem, frase criativa, um gráfico ou analogia, o que importa é a facilitação do precesso de trazer a tona alguma memória.</p>

    <h4 >Modos de pensamento</h4>
    <p >No mesmo livro da escritora norte americana é apresentado os modos de pensamento que foram condensados por ela em dois termos, modo difuso e modo focado, essas modalidades de pensamento expressam as duas funções com as quais o nosso cérebro opera, ora ele está em modo difuso e hora ele está no modo focado, mas nunca funcionado nos dois modos ao mesmo tempo. E a chave para um bom aprendizado é a alternância desses modos, porque é de consenso na neurociencia que o modo focado gera conteúdo, ou seja material para ser armazenado, porque quando estamos estudando seja fazendo anotações em um livro ou durante uma aula é esse modo que toma a frente, porém esse modo tem as suas limitações, ele trabalha de uma forma muito focada, perdendo o escopo global e é aí que o difuso entra, o difuso tem a sua principal função consolidar esse material conquistado no momento do estudo, além de que o difuso tem uma característica interresante que é a de operar em várias área do cérebro trazendo informações de diferentes naturezas para o indivíduo, por isso o nome difuso, porque o funcionamento do nosso cérebro está diluído em várias regiões do cérebro e não só em uma como é o focado.</p>
   

    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
      </svg>
   
</div>
{% endblock %}

home/templates/home/course_page.html
{% extends 'home/layout.html' %}
{% block title %}{{course.name}}{% endblock %}
{% block body %}
<h1 class="h">{{course.name}}</h1>
<div class="text_content">
    <p>{{ course.content|safe }}</p>
    <p><a href="{% url 'courses' %}">Clique aqui</a> para voltar para o página dos cursos.</p>
</div>
{% endblock %}

home/templates/home/home.html
{% extends 'home/layout.html' %}

{% block title %} Home {% endblock %}

{% block body %}
<div class="content">
    <div class="text_content">
    <h1 >Ensaios sobre a inteligência feito por um estudante do ensino médio</h1>
    <p >Nas palestras do Prof Pier, um italo brasileiro notório nas discussões sobre aprendizado e inteligência, o mesmo enfatizava o fato de que a inteligência não é uma característica nata de algúem, mas que como qualquer outra habilidade que o ser humano pode carregar, a capacidade de "ser inteligente" é algo que tem como aprender e desenvolver, ou seja é possível exercitar esse tal dom da inteligência. </p>
    <p >Os estudos são essencias para a vida de qualquer pessoa, pois eles edificam o sujeito, permitindo que ele aprenda novas habilidades as quais podem ser empregadas no seu dia a dia para resolver problemas ou para melhorar algum campo da existencia humana, como a esfera emocional, intelectual e a ate mesmo a espiritual.</p>
    <h2 >Inteligência para a neurociência</h2>
    <p >Estudos contemporâneos da neurociência indicam que é possível qualquer pessoa aumentar o seu conhecimento sobre determinado assunto, seja com maior ou menor esforço a depender de deficiencias cognitivas, mas sempre há espaço de aprendizagem, isso se da pela neuroplasticidade, termo que define a capacidade do nosso cérebro, órgão do corpo humano mais complexo, tem de se moldar de acordo com os estímulos o qual é exposto.</p>

    <h2 >Como aprendemos</h2>
    <p >O aprendizado humano ocorre por meio da visualização de informações e a operação dessas para a realização de alguma atividade - uma questão de prova por exemplo-, por isso o fato de revisar e exercitar essa nova habilidade é de extrema importância, pois somente assim esse conhecimeto é consolidado.</p>
    <h3 >Como apender e lembrar de algo</h3>
    <p >O livro "Aprendendo A Aprender" de Barbara Okley aponta que para aprendermos algo, e com efeito lembrarmos disso , é necessário que exista um dado  e que ele seja memorável, ou seja exista elementos nesse conteúdo estudado  que facilitem a sua retomada da memória, por isso que quanto mais 'inputs' mentais melhor, porque aumentam as chances de você recordar do conteúdo, esses inputs podem ser uma imagem, frase criativa, um gráfico ou analogia, o que importa é a facilitação do precesso de trazer a tona alguma memória.</p>

    <h4 >Modos de pensamento</h4>
    <p >No mesmo livro da escritora norte americana é apresentado os modos de pensamento que foram condensados por ela em dois termos, modo difuso e modo focado, essas modalidades de pensamento expressam as duas funções com as quais o nosso cérebro opera, ora ele está em modo difuso e hora ele está no modo focado, mas nunca funcionado nos dois modos ao mesmo tempo. E a chave para um bom aprendizado é a alternância desses modos, porque é de consenso na neurociencia que o modo focado gera conteúdo, ou seja material para ser armazenado, porque quando estamos estudando seja fazendo anotações em um livro ou durante uma aula é esse modo que toma a frente, porém esse modo tem as suas limitações, ele trabalha de uma forma muito focada, perdendo o escopo global e é aí que o difuso entra, o difuso tem a sua principal função consolidar esse material conquistado no momento do estudo, além de que o difuso tem uma característica interresante que é a de operar em várias área do cérebro trazendo informações de diferentes naturezas para o indivíduo, por isso o nome difuso, porque o funcionamento do nosso cérebro está diluído em várias regiões do cérebro e não só em uma como é o focado.</p>
    </div>
</div>
{% endblock %}

home/templates/home/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/home/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="shortcut icon" href="../../static/home/images/brain_882998.png" type="image/x-icon">
    <script src="../../static/home/basic.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body id="body">
    <header>
        <nav id="nav">
            <a class="logo" href="{% url 'home' %}">Estudologia</a>
            <div class="mobile_menu">
                <div class="nav_btn">  
                    <i onclick='showMenu()' class="fa-solid fa-bars"></i>
                </div>        
            </div>
            <ul class="nav_list">
                <input type="checkbox" name="checkbox" class="checkbox" id="chk" onchange="change_theme(document.body.className)">
                <label class="theme_label" for="chk">
                    <i class="fa-solid fa-moon"></i>
                    <i class="fa-solid fa-sun"></i>
                    <div class="ball"></div>
                </label>
                <li class="nav_link"><a href="{% url 'courses' %}">Cursos</a></li>
                <li class="nav_link"><a href="{% url 'hub' %}">Apps</a></li>
                <li class="nav_link"><a href="{% url 'about_me' %}">Sobre Mim</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'historic_hub' %}">Histórico</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li class="nav_link"><a href="{% url 'login' %}">Login</a></li>
                <li class="nav_link"><a href="{% url 'register' %}">Registrar</a></li>
                {% endif %}
            </ul>     
        </nav>
    </header>
    <main>
        {% block body %}{% endblock %}
    </main>
    
</body>
</html>

home/templates/home/login.html
{% extends 'home/layout.html' %}
{% load static %}
{% block title %}Login{% endblock %}

{% block body %}


<style>
    label{
        display: flex;
        align-items: center;
        margin: 0;
    }

    input[type = 'text'], input[type = 'password']{
        border: none;
        border-radius: 10px;
        outline: none;
        padding: 0 10px;
        background-color: #DEE4E7;
    }
    .submit_btn_area{
        margin-top :10px ;
        width: 50vw;
    }
    input[type = 'submit']{
        background-color: #007bff;
        width: 25vw;
        border-radius: 40px;
        line-height: 30px;
        outline: none;
        border: none;
        color: white;
        font-weight: bold;
    }
    .alert{
        margin-top: 10px;
        color: black;
        width: 30vw;
    }
</style>

<script>
    document.addEventListener("DOMContentLoaded", ()=>{
        document.querySelector('#id_username').setAttribute('placeholder', 'Usuário')
        document.querySelector('#id_username').setAttribute('autocomplete', 'off')
        document.querySelector('#id_username').style.textAlign = 'left';
        document.querySelector('#id_password').setAttribute('placeholder', 'Senha')
        document.querySelector('#id_password').style.textAlign = 'left';
        // Use to the site now show the error msg if it is empty
        if(document.querySelector(".alert").textContent == '\n            \n        '){
            document.querySelector(".alert").style.display = 'none';
        }
        
    })
  
</script>

<main>
    <div class="centralized">
        <h1 class="h">Login</h1>
    </div>
<div class="content">
    <div class="text_content">
    <form action="{% url 'login' %}" method="POST">
        <div class="form_area">
            {{form}}
            {% csrf_token %}
            <div class="centralized-text">
                <div class="submit_btn_area">
                    <input type="submit" value="Enviar">
                </div>
            </div>
        </div>
    </form>
    <div class="centralized">
        <div class="alert alert-danger" role="alert">
            <span>{{msg}}</span>
        </div>
    </div>
    </div>
</div>
</main>

{% endblock %}

home/templates/home/register.html
{% extends 'home/layout.html' %}

{% block title %}Cadastro{% endblock %}

{% block body %}
<style>
    label{
        display: flex;
        align-items: center;
        margin: 0;
    }

    input[type = 'text'], input[type = 'password'], input[type = 'email']{
        border: none;
        border-radius: 10px;
        outline: none;
        padding: 0 10px;
        background-color: #DEE4E7;
        height: 40px;
    }
    .submit_btn_area{
        margin-top :10px ;
        width: 50vw;
    }
    input[type = 'submit']{
        background-color: #007bff;
        width: 25vw;
        border-radius: 40px;
        line-height: 30px;
        outline: none;
        border: none;
        color: white;
        font-weight: bold;
    }
    .alert{
        margin-top: 10px;
        color: black;
        width: 30vw;
    }
</style>


<script>
    document.addEventListener("DOMContentLoaded", ()=>{
        document.querySelector("#id_username").style.textAlign = 'left';
        document.querySelector('#id_password').setAttribute('placeholder', 'Senha');
        document.querySelector('#id_password').style.textAlign = 'left';
        document.querySelector('#id_confirm_password').setAttribute('placeholder', 'Confirme a Senha');
        document.querySelector('#id_confirm_password').style.textAlign = 'left';
        document.querySelector("#span_msg").addEventListener("change", ()=>{
            document.querySelector("#span_msg").style.display = 'block'
        })
        // Use to the site now show the error msg if it is empty
        if(document.querySelector("#span_msg").textContent != ''){
            document.querySelector(".centralized-alert").style.display = 'flex'
        }
           
    })
</script>

<main>
    <div class="centralized">
        <h1 class="h">Registrar</h1>
    </div>
<div class="content">
    <div class="text_content">
    <form action="{% url 'register' %}" method="POST">
        {{message}}
        <div class="form_area">
            {{form}}
            {%csrf_token %}
            <div class="centralized-text">
                <div id="submit_btn_area">
                    <input type="submit" value="Enviar" >
                    
                </div>
                
            </div>
            <div class="centralized-alert">
                <div class="alert alert-danger" role="alert">
                   <span id="span_msg">{{msg}}</span>
                </div>
            </div>
        </div>
    </form>
    <p>OBS: Não uma senha que esteja sendo usada em outros registros, recomendo usar uma senha especifica para o estudologia e de preferência bem forte, para facilitar use <a href="https://www.lastpass.com/pt/features/password-generator" rel="external" target="blank">esse site</a> para gerar uma senha forte</p>
    </div>
</div>
</main>

{% endblock %}